name: Atala QA pages

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

permissions:
  id-token: write

jobs:
  release-page:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Dokka
        run: ./gradlew dokkaHtml

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
