name: Build and test

on:
  pull_request:
    branches:
      - "main"

jobs:
  build-and-test:
    name: "Build and test"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Build and test
        run: ./gradlew build

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: build/test-results/**/*.xml

      - name: Publish Detekt Results
        run: cat build/reports/detekt/detekt.md >> $GITHUB_STEP_SUMMARY
