name: Atala QA Release

on:
  push:
    branches:
      - "main"

jobs:
  build-and-test-enterprise-services:
    name: "Build and test"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: enterprise-services

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install
        run: npm install

      - name: Build TS models with Orval
        run: npm run orval

      - name: Eslint
        run: npm run lint

      - name: Generate Prisma
        run: npx prisma generate

      - name: Build
        run: npm run build

      - name: Run unit tests
        run: npm run test

      - name: Run integration tests
        run: npm run test:smoke

      - name: Run Dockerfile linting
        run: npm run lint:dockerfile

      - name: Check test coverage
        run: npm run coverage:total && npm run coverage:check

      - name: Run OAS lint
        run: npx @stoplight/spectral-cli lint "enterprise-services/api-spec/enterprise-services-spec.yml"
