name: Atala QA Release

on:
  push:
    branches:
      - "main"

jobs:
  build-and-test-enterprise-services:
    name: "Release"
    runs-on: ubuntu-latest

    steps:
      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v2

      - name: Checkout
        uses: actions/checkout@v3
